### ISSUE TITLE
Question: How does the relative path of the image get into the array »$match[1]«? 

### ISSUE THREAD

**Issue by PetersOtto** [pftnhr/yellow-absoluteimage#1]
Hi Robert,
unfortunately I am not a great `php` programmer. I'm just trying to understand your code. Unfortunately I can't do it. Perhaps you can give me a tip. How does the relative path of the image get into the array `$match[1]`?

**Comment by pftnhr** [comment]
To be honest, I have no idea either. I suspect there's magic involved. No, seriously, I put the code together from other extensions and am now happy that it works. 😄

**Comment by PetersOtto** [comment]
I think we have very similar ways of working. 😄 I can make good use of your code for my own extension. Thx!

**Comment by pftnhr** [comment]
You're welcome 😄
